quiz2/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :ideas do
    resources :reviews, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end

  post "/ideas/:idea_id/likes/on_index" => "likes#create_on_index", :as => :like_idea_on_index
  delete "/ideas/:idea_id/likes/:id/on_index" => "likes#destroy_on_index", :as => :destroy_idea_on_index

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  root "ideas#index"
end

quiz2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

quiz2/app/models/idea.rb
class Idea < ApplicationRecord
    belongs_to :user 
    has_many :reviews, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :likers, through: :likes, source: :user

    validates :title, presence: true
    validates :description, presence: true
end

quiz2/app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
  belongs_to :idea

  validates :idea_id, uniqueness: { scope: :user_id }
end

quiz2/app/models/review.rb
class Review < ApplicationRecord
    belongs_to :idea
    belongs_to :user
  
    validates :body, presence: true    
end

quiz2/app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :ideas, dependent: :destroy
    has_many :reviews, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :liked_ideas, through: :likes, source: :idea
    
    before_validation :downcase_email

    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :email, presence: true, uniqueness: {case_sensitive: false}
    validates :password_digest, presence: true


    private

    def downcase_email
        self.email = self.email.downcase
    end
end

quiz2/app/controllers/ability.rb
class Ability
    include CanCan::Ability

  def initialize(user)
    user ||= User.new

    alias_action :create, :read, :update, :delete, to: :crud

    can :crud, Idea do |idea|
      user == idea.user
    end

    can :crud, Review do |review|
      user == review.user
    end

    can :destory, Like do |like|
      user == like.user
    end

  end
end

quiz2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

quiz2/app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
    before_action :find_idea, except: [:index, :new, :create]
    before_action :authenticate_user!, except: [:index, :show]
    before_action :authorize_user!, only: [:edit, :update, :destroy]

    def new
        @idea = Idea.new
    end

    def create
        @idea = Idea.new idea_params
        @idea.user = current_user
        if @idea.save
            flash[:notice] = "Successfully Created an Idea"
            redirect_to idea_path(@idea)
        else  
            render :new, status: 303
        end
    end

    def show
        @reviews = @idea.reviews.order(created_at: :desc)
        @review = Review.new
        @like = @idea.likes.find_by(user: current_user)
    end

    def index
        @ideas = Idea.order updated_at: :desc
        
    end

    def edit

    end

    def update
        if @idea.update idea_params
            redirect_to idea_path(@idea)
        else
            render :edit, status: 303
        end
    end

    def destroy
        @idea.destroy
        redirect_to ideas_path, notice: "Idea Deleled"
    end

    private

    def authorize_user!
        redirect_to root_path, alert: "Not Authorized" unless can?(:crud, @idea)
    end

    def find_idea
        @idea = Idea.find params[:id]
    end

    def idea_params
        params.require(:idea).permit!
    end

end

quiz2/app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :authenticate_user!

    def create
        like = Like.new
        idea = Idea.find params[:idea_id]
        like.idea = idea
        like.user = current_user
        if like.save
            redirect_to idea_path(idea), notice: "Thanks For Your Like"
        else  
            redirect_to idea_path(idea), alert: "Cannot Like"
        end

    end

    def destroy
        idea = Idea.find params[:idea_id]
        like = current_user.likes.find params[:id]
        like.destroy
        redirect_to idea_path(idea), notice: "Like Removed"
    end

    def create_on_index
        like = Like.new
        idea = Idea.find params[:idea_id]
        like.idea = idea
        like.user = current_user
        if like.save
            redirect_to ideas_path, notice: "Thanks For Your Like"
        else  
            redirect_to ideas_path, alert: "Cannot Like"
        end
    end

    def destroy_on_index
        idea = Idea.find params[:idea_id]
        like = current_user.likes.find params[:id]
        like.destroy
        redirect_to ideas_path, notice: "Like Removed"
    end
end

quiz2/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :authenticate_user!

    def create
        @idea = Idea.find params[:idea_id]
        @review = Review.new params.require(:review).permit!
        @review.idea = @idea
        @review.user = current_user
        if @review.save
            redirect_to idea_path(@idea), notice: "Review Posted"
        else   
            @reviews = @idea.reviews.order(created_at: :desc)
            render 'ideas/show', status: 303
        end
    end

    def destroy
        @review = Review.find params[:id]
        @idea = Idea.find params[:idea_id]
        if can?(:crud, @review)
            @review.destroy
            redirect_to idea_path(@idea), notice: "Review Deleted"
        else 
            
            redirect_to idea_path(@idea), notice: "Not Authorized To Delete This"
        end
    end
end

quiz2/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
        @user = User.find_by_email params[:email]
        if @user && @user.authenticate(params[:password]) # why this method requires parentheses?
            session[:user_id] = @user.id
            redirect_to root_path, notice: "Welcome Back"
        else  
            render :new, status: 303
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged Out"
    end
end

quiz2/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new params.require(:user).permit!
        if @user.save
            session[:user_id] = @user.id 
            redirect_to root_path, notice: "Successfully Signed Up"
        else  
            render :new, status: 303
        end
    end
end

quiz2/app/helpers/application_helper.rb
module ApplicationHelper
end

quiz2/app/helpers/ideas_helper.rb
module IdeasHelper
end

quiz2/app/helpers/likes_helper.rb
module LikesHelper
end

quiz2/app/helpers/reviews_helper.rb
module ReviewsHelper
end

quiz2/app/helpers/sessions_helper.rb
module SessionsHelper
end

quiz2/app/helpers/users_helper.rb
module UsersHelper
end

quiz2/app/views/ideas/_form.html.erb
<%= form_with(model: @idea) do |form| %>
    <div>
        <%= form.label :title, class:"form-label" %>
        <br>
        <%= form.text_field :title, class:"form-control" %>  
    </div>
    <div>
        <%= form.label :description, class:"form-label" %>
        <br>
        <%= form.text_area :description, cols: 50, rows: 6, class:"form-control" %>  
    </div>
    <%= form.submit "Submit", class:"mt-3 btn btn-info" %> 
<% end %> 

quiz2/app/views/ideas/edit.html.erb
<h1 class="mb-3">Edit Idea</h1>
<% if @idea.errors.any? %>
    <p><%= @idea.errors.full_messages.join('; ')%></p>
<% end %> 
<%= render "form" %> 

quiz2/app/views/ideas/index.html.erb
<% @ideas.each do |idea| %>
    <div class="card mb-3 bg-yellow">
        <div class="card-body">
            <h5 class="card-title"><%= link_to idea.title, idea_path(idea),class:"pink-title" %></h5>
            <p class="card-text"><%= idea.description %></p>
            <p class="card-text">By <%= idea.user.first_name %></p>
            <p class="card-text">Likes: <%= idea.likes.count %></p>
            <% @like = idea.likes.find_by(user: current_user) %> 
            <% if @like %>
                <%= button_to "Liked", destroy_idea_on_index_path(idea, @like), method: :delete, class: "btn btn-primary" %> 
            <% else %>
                <%= button_to "Like", like_idea_on_index_path(idea), method: :post, class: "btn btn-primary" %> 
            <% end %> 
        </div>
    </div>
<% end %>  

quiz2/app/views/ideas/new.html.erb
<h1 class="mb-3">New Idea</h1>
<% if @idea.errors.any? %>
    <p><%= @idea.errors.full_messages.join('; ')%></p>
<% end %> 
<%= render "form" %> 

quiz2/app/views/ideas/show.html.erb
<h2 class="mb-3"><%= @idea.title %></h2>
<p><%= @idea.description %></p>
<p>Created by: <%= @idea.user.first_name %></p>

<div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
    <% if can?(:crud, @idea) %>
        <div class="btn-group me-2" role="group">
        <%= button_to "Edit", edit_idea_path(@idea), method: :get, class: "btn btn-warning" %> 
        </div>
        <div class="btn-group me-2" role="group">
        <%= button_to "Delete", idea_path(@idea), method: :delete, form: { data: { turbo_confirm: "Are you sure?" } }, class: "btn btn-info" %> 
        </div>
    <% end %> 
    
    <% if @like.present? %>
    <%= button_to "Liked", idea_like_path(@idea, @like), method: :delete, class: "btn btn-primary mb-3" %> 
    <% else %>
        <%= button_to "Like", idea_likes_path(@idea), method: :post,class: "btn btn-primary mb-3" %> 
    <% end %> 

    <h5 class="ms-auto">Likes: <%= @idea.likes.count %></h5>
</div>


<% if @review.errors.any? %> 
    <% @review.errors.full_messages.each do |msg| %> 
        <p><%= msg %> </p>
    <% end %> 
<% end %> 
<%= form_for [@idea, @review] do |f| %>
    <%= f.text_area :body, class: "form-control" %>
    <br>
    <%= f.submit "Leave Review", class: "btn btn-info mb-5" %>  
<% end %> 
<% @reviews.each do |review| %>
    <p><%= review.body %></p>
    <p>By <%= review.user.first_name %></p>
    <% if can?(:crud, review) %>
        <%= button_to "Delete", idea_review_path(@idea, review), method: :delete, form: { data: { turbo_confirm: "Are you sure?" } }, class:"btn btn-primary" %> 
    <% end %>  
    <hr>
<% end %> 

quiz2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

quiz2/app/views/users/new.html.erb
<h1 class="mb-3">Sign Up</h1>

<% if @user.errors.any? %>
    <p><%= @user.errors.full_messages.join('; ')%></p>
<% end %> 
<%= form_for @user do |f| %>
    <div class="mb-3">
        <%= f.label :first_name, class:"form-label" %>
        <%= f.text_field :first_name, class: "form-control" %>  
    </div>
    <div class="mb-3">
        <%= f.label :last_name, class:"form-label" %>
        <%= f.text_field :last_name, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= f.label :email, class:"form-label" %>
        <%= f.email_field :email, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= f.label :password, class:"form-label" %>
        <%= f.password_field :password, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= f.label :password_confirmation, class:"form-label" %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>
      <%= f.submit "Sign Up" , class:"btn btn-info"%>
<% end %> 